name: Deploy Infrastructure

on:
  push:
    branches: [ "master" ]
    paths:
      - 'infra/**'


permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::072859661869:role/oidc-deploy
        aws-region: us-east-1      

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: quest-app-ecr
        template: infra/ecr_deploy.yml
        no-fail-on-empty-changeset: "1"

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: quest-app
        template: infra/testing.yml
        no-fail-on-empty-changeset: "1"